apiVersion: v1
kind: Service
metadata:
  name: automated-devops-service
spec:
  selector:
    app: automated-devops-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
